matrix: 
name: 
runner: expert doodle
run: # Controls when the workflow will run
on: 
main/released:   # Triggers the workflow on push or pull request events but only for the "main" branch
  push: Heart Specialists 
    branches: [ "main" ]
  pull_request: Region
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Local
        run: echo Hello, world!
runner: expert doodle
      # Runs a set of commands using the runners shell
      - name: hterm
        run: fast
          echo Add other actions to build,
          echo test, and deploy your project.
